export const characters = [
  { 
    id: 'asher', 
    name: '애셔 셰퍼드', 
    englishName: ' ', 
    image1: 'https://i.postimg.cc/RhLxDDv4/polla-0003s-0001-leieo-2.jpg',
    image1Desc: '오스카가 찍어줌',
    image2: 'https://i.postimg.cc/vZHbpbgZ/polla-0003s-0000-leieo-3.jpg',
    image2Desc: '쿼터백',
    image3: 'https://i.postimg.cc/sgwDXvdS/polla-0003s-0002-leieo-1.jpg',
    image3Desc: '편하게?',
    image4: 'https://i.postimg.cc/vH7ZJ00x/polla-0003s-0003-aesyeo.jpg',
    image4Desc: '증명사진',
    studentIdImage: 'https://i.postimg.cc/4NLRZ83r/hagsaengjeung-0011-aesyeo(gugjegwangyehag)-bogsa.png',
    stickerImage: 'https://i.postimg.cc/G3P7Gr4X/2.png',
    sticker2Image: 'https://i.postimg.cc/BQW24w44/ap.png',
    bgNoteImage: 'https://i.postimg.cc/pXxS6yNR/test6.png'
  },
  { 
    id: 'max', 
    name: '맥스 로저스', 
    englishName: ' ', 
    image1: 'https://i.postimg.cc/vTs4JT6v/polla-0000s-0000-leieo-13.jpg',
    image1Desc: '무비나잇',
    image2: 'https://i.postimg.cc/Hx75GFvY/polla-0000s-0002-leieo-11.jpg',
    image2Desc: '라인배커',
    image3: 'https://i.postimg.cc/FsvSqWj2/polla-0000s-0001-leieo-12.jpg',
    image3Desc: '잠옷 뭐임',
    image4: 'https://i.postimg.cc/fWBH8sNX/polla-0000s-0003-maegseu.jpg',
    image4Desc: '증명사진',
    studentIdImage: 'https://i.postimg.cc/TPkrxd3d/jemog-eobs-eum-1-0009-maegseu(sahoehag)-bogsa.png',
    stickerImage: 'https://i.postimg.cc/hPp2Zrbr/3.png',
    sticker2Image: 'https://i.postimg.cc/BQW24w44/ap.png',
    bgNoteImage: 'https://i.postimg.cc/prqL3TZy/baegyeongmemo-0010-maegseu.png'
  },
  { 
    id: 'eric', 
    name: '에릭 멘데즈', 
    englishName: ' ', 
    image1: 'https://i.postimg.cc/3wmS1D8h/polla-0002s-0001-leieo-5.jpg',
    image1Desc: '뻗었대요ㅋㅋ',
    image2: 'https://i.postimg.cc/qM196nqB/polla-0002s-0000-leieo-6.jpg',
    image2Desc: '애착 바이크',
    image3: 'https://i.postimg.cc/8kHYxWhr/polla-0002s-0002-leieo-4.jpg',
    image3Desc: '맨날 야차뜨는 와이드 리시버',
    image4: 'https://i.postimg.cc/YCsKZgBs/polla-0002s-0003-elig.jpg',
    image4Desc: '증명사진',
    studentIdImage: 'https://i.postimg.cc/1t2wgvFB/jemog-eobs-eum-1-0010-elig(seupocheumaketing)-bogsa.png',
    stickerImage: 'https://i.postimg.cc/CKWPHxC3/1.png',
    sticker2Image: 'https://i.postimg.cc/BQW24w44/ap.png',
    bgNoteImage: 'https://i.postimg.cc/2SP8sg4Q/baegyeongmemo-0009-elig.png'
  },
  { 
    id: 'oscar', 
    name: '오스카 밀러', 
    englishName: ' ', 
    image1: 'https://i.postimg.cc/nztVz5ch/polla-0001s-0000-leieo-10.jpg',
    image1Desc: '다음날 아침',
    image2: 'https://i.postimg.cc/gjs21Dpc/polla-0001s-0002-leieo-7.jpg',
    image2Desc: '세이프티',
    image3: 'https://i.postimg.cc/SNQsCwL2/polla-0001s-0001-leieo-9.jpg',
    image3Desc: '파티보이',
    image4: 'https://i.postimg.cc/0NKrrDYZ/polla-0001s-0003-oseuka.jpg',
    image4Desc: '증명사진',
    studentIdImage: 'https://i.postimg.cc/4xQ68bCY/jemog-eobs-eum-1-0008-oseuka(dijain-midieoateu)-bogsa.png',
    stickerImage: 'https://i.postimg.cc/yd4j3rBy/4.png',
    sticker2Image: 'https://i.postimg.cc/BQW24w44/ap.png',
    bgNoteImage: 'https://i.postimg.cc/sxDVPzRb/baegyeongmemo-0008-oseuka.png'
  },
  { 
    id: 'nathan', 
    name: '네이슨 울프', 
    englishName: ' ', 
    image1: 'https://i.postimg.cc/KvKWq521/polla-0007s-0000-leieo-22.jpg',
    image1Desc: '서프섀크에서',
    image2: 'https://i.postimg.cc/Jn1gpV12/polla-0007s-0001-leieo-21.jpg',
    image2Desc: '해변파티',
    image3: 'https://i.postimg.cc/0jXL6W1T/polla-0007s-0002-leieo-20.jpg',
    image3Desc: '여름의 남자',
    image4: 'https://i.postimg.cc/jd5TsNrx/polla-0007s-0003-neiseun.jpg',
    image4Desc: '증명사진',
    studentIdImage: 'https://i.postimg.cc/XYbKc1zx/jemog-eobs-eum-1-0007-neiseun(gyeong-yeonghag)-bogsa.png',
    stickerImage: 'https://i.postimg.cc/wMFQPqJH/5.png',
    sticker2Image: 'https://i.postimg.cc/V6rbcXhq/sf.png',
    bgNoteImage: 'https://i.postimg.cc/13NyrMLx/baegyeongmemo-0007-neiseun.png'
  },
  { 
    id: 'isaac', 
    name: '아이작 도노반', 
    englishName: ' ', 
    image1: 'https://i.postimg.cc/RVfkCTb8/polla-0006s-0001-leieo-37.jpg',
    image1Desc: '파도',
    image2: 'https://i.postimg.cc/zfppXLrc/polla-0006s-0000-leieo-36.jpg',
    image2Desc: '총각 곡쥐 보여',
    image3: 'https://i.postimg.cc/6q8MPBFY/polla-0006s-0002-leieo-38.jpg',
    image3Desc: '오르카',
    image4: 'https://i.postimg.cc/3wZf4Sgn/polla-0006s-0003-aijag.jpg',
    image4Desc: '증명사진',
    studentIdImage: 'https://i.postimg.cc/DfRPmwdf/jemog-eobs-eum-1-0006-aijag(geonchughag)-bogsa.png',
    stickerImage: 'https://i.postimg.cc/KvvNTTSg/6.png',
    sticker2Image: 'https://i.postimg.cc/V6rbcXhq/sf.png',
    bgNoteImage: 'https://i.postimg.cc/B6Jss3tn/baegyeongmemo-0006-aijag.png'
  },
  { 
    id: 'raul', 
    name: '라울 헤이즈', 
    englishName: ' ', 
    image1: 'https://i.postimg.cc/63nr4ysF/polla-0004s-0000-leieo-35.jpg',
    image1Desc: '빈센트가 찍어줌!',
    image2: 'https://i.postimg.cc/YCDfJ5fX/polla-0004s-0001-leieo-34.jpg',
    image2Desc: '취하셨군요',
    image3: 'https://i.postimg.cc/gc3snBm8/polla-0004s-0002-leieo-33.jpg',
    image3Desc: '서핑 후',
    image4: 'https://i.postimg.cc/1zTBNk8d/polla-0004s-0003-laul.jpg',
    image4Desc: '증명사진',
    studentIdImage: 'https://i.postimg.cc/3RcWSWJD/jemog-eobs-eum-1-0004-laul(maketing)-bogsa.png',
    stickerImage: 'https://i.postimg.cc/50V52Yqk/8.png',
    sticker2Image: 'https://i.postimg.cc/V6rbcXhq/sf.png',
    bgNoteImage: 'https://i.postimg.cc/MHF8yj5j/baegyeongmemo-0005-laul.png'
  },
  { 
    id: 'vincent', 
    name: '빈센트 클라인', 
    englishName: ' ', 
    image1: 'https://i.postimg.cc/RCtswZQ0/polla-0005s-0001-leieo-31.jpg',
    image1Desc: '굿 보이~',
    image2: 'https://i.postimg.cc/Bvv7F5Mb/polla-0005s-0000-leieo-30.jpg',
    image2Desc: '여름밤',
    image3: 'https://i.postimg.cc/sDpLCgvL/polla-0005s-0002-leieo-32.jpg',
    image3Desc: '8월의 어느날',
    image4: 'https://i.postimg.cc/50TrbHBD/polla-0005s-0003-binsenteu.jpg■',
    image4Desc: '증명사진',
    studentIdImage: 'https://i.postimg.cc/v84vQVnr/jemog-eobs-eum-1-0005-binsenteu(sahoehag)-bogsa.png',
    stickerImage: 'https://i.postimg.cc/Cx9H96ZB/7.png',
    sticker2Image: 'https://i.postimg.cc/V6rbcXhq/sf.png',
    bgNoteImage: 'https://i.postimg.cc/FHcQLzLH/baegyeongmemo-0004-binsenteu.png'
  },
  { 
    id: 'blake', 
    name: '블레이크 닐', 
    englishName: ' ', 
    image1: 'https://i.postimg.cc/435Zf1nN/polla-0001s-0000-leieo-18.jpg',
    image1Desc: '니트: 죽여줘...',
    image2: 'https://i.postimg.cc/Jnp1qQWF/polla-0001s-0002-leieo-14.jpg',
    image2Desc: '체크 잘어울린당',
    image3: 'https://i.postimg.cc/VLrYqMZW/polla-0001s-0001-leieo-15.jpg',
    image3Desc: '도서관',
    image4: 'https://i.postimg.cc/25f886wZ/polla-0001s-0003-beulleikeu.jpg',
    image4Desc: '증명사진',
    studentIdImage: 'https://i.postimg.cc/KY5MNZMs/jemog-eobs-eum-1-0001-beulleikeu(singyeong-gwahag)-bogsa.png',
    stickerImage: 'https://i.postimg.cc/yNF9t6CH/12.png',
    sticker2Image: 'https://i.postimg.cc/SQ9zT78P/sigma.png',
    bgNoteImage: 'https://i.postimg.cc/G230VjSL/baegyeongmemo-0003-beulleikeu.png'
  },
  { 
    id: 'joshua', 
    name: '조슈아 매티스', 
    englishName: ' ', 
    image1: 'https://i.postimg.cc/pXzdNzQb/polla-0000s-0002-leieo-23.jpg',
    image1Desc: '산책할래?',
    image2: 'https://i.postimg.cc/0rghd6rw/polla-0000s-0000-leieo-25.jpg',
    image2Desc: '비어퐁',
    image3: 'https://i.postimg.cc/QM0GGxYn/polla-0000s-0001-leieo-24.jpg',
    image3Desc: '강의실',
    image4: 'https://i.postimg.cc/y65K8x6s/polla-0000s-0003-josyua.jpg',
    image4Desc: '증명사진',
    studentIdImage: 'https://i.postimg.cc/TYyn6Mz6/jemog-eobs-eum-1-0000-josyua(gyeong-yeonghag)-bogsa.png',
    stickerImage: 'https://i.postimg.cc/6QsnM2SX/11.png',
    sticker2Image: 'https://i.postimg.cc/SQ9zT78P/sigma.png',
    bgNoteImage: 'https://i.postimg.cc/yYgMMxng/baegyeongmemo-0002-josyua.png'
  },
  { 
    id: 'colin', 
    name: '콜린 래틀리프', 
    englishName: ' ', 
    image1: 'https://i.postimg.cc/xTxzCKJx/polla-0003s-0000-leieo-29.jpg',
    image1Desc: '그러다 다 흘린다',
    image2: 'https://i.postimg.cc/BbN12Fmr/polla-0003s-0001-leieo-27.jpg',
    image2Desc: '강의 전',
    image3: 'https://i.postimg.cc/wBsJn7Bq/polla-0003s-0002-leieo-26.jpg',
    image3Desc: '슬립오버',
    image4: 'https://i.postimg.cc/mZ33bzy6/polla-0003s-0003-kollin.jpg',
    image4Desc: '증명사진',
    studentIdImage: 'https://i.postimg.cc/CKwZdWQ8/jemog-eobs-eum-1-0003-kollin(keompyuteogonghag)-bogsa.png',
    stickerImage: 'https://i.postimg.cc/Gt3kvWfJ/9.png',
    sticker2Image: 'https://i.postimg.cc/SQ9zT78P/sigma.png',
    bgNoteImage: 'https://i.postimg.cc/VvT3SPsY/baegyeongmemo-0001-kollin.png'
  },
  { 
    id: 'jay', 
    name: '제이 벤슨', 
    englishName: ' ', 
    image1: 'https://i.postimg.cc/KjYYSH5V/polla-0002s-0000-leieo-19.jpg',
    image1Desc: '테니스',
    image2: 'https://i.postimg.cc/Vk0dk2Pp/polla-0002s-0001-leieo-16.jpg',
    image2Desc: '파티',
    image3: 'https://i.postimg.cc/D0C8STZn/polla-0002s-0002-leieo-17.jpg',
    image3Desc: '공강시간',
    image4: 'https://i.postimg.cc/76kCc9cp/polla-0002s-0003-jei.jpg',
    image4Desc: '증명사진',
    studentIdImage: 'https://i.postimg.cc/BZz1N7Xg/jemog-eobs-eum-1-0002-jei(simlihag)-bogsa.png',
    stickerImage: 'https://i.postimg.cc/X7Jfq0d3/10.png',
    sticker2Image: 'https://i.postimg.cc/SQ9zT78P/sigma.png',
    bgNoteImage: 'https://i.postimg.cc/HkbfLNqm/baegyeongmemo-0000-jei.png'
  }
];
